apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-6aox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-6aox
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-6aox
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-6aox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-6aox
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-gpwi-tenant/appstudio/dc-metro-map-6aox@sha256:6e47d518e6c6d711ea3f5e0343d9a616905f0949379061c09d27203a4bae47e4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
